### PR TITLE
:sparkles: Support for hyperlinked resources

### PR DESCRIPTION
**Pull request by stevenbal**
Related to https://github.com/VNG-Realisatie/gemma-zaken/discussions/1960#discussioncomment-2389343

Required for https://github.com/open-zaak/open-zaak/pull/1138

Changes:
* Add support for hyperlinked API resources
* Allow overriding of model keys used in inclusions
* Optional usage of absolute paths for nested inclusions
* Add github workflow to replace Travis CI
* Extra config options to define allowed include paths and allowed include actions

### CODE REVIEW

**Comment by sergei-maertens** [comment]
@kdleijer - any chance you can give this a review? :)

**Comment by kdleijer** [comment]
> @kdleijer - any chance you can give this a review? :)

Sure ! For some reason all communication went into my spam filter.
I've succesfully tested this branch against ours (and also the complete product suite).
Good job and many thanks for the contributions !

I will merge it with one remark:
`get_allowed_paths` now has an additional parameter that needs to be supplied and is not defaulted. Therefore this is a breaking change.

**Comment by sergei-maertens** [comment]
cc @stevenbal

**Comment by stevenbal** [comment]
> I will (eventually) merge it with one remark:
get_allowed_paths now has an additional parameter that needs to be supplied and is not defaulted. Therefore this is a breaking change.

I made `view` a keyword argument in the latest commit

**Pull request merged**
